apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      # targetPort: 80 - eh feito esse bind implicitamente
      nodePort: 30000 # porta que permitirah o acesso externo
  selector:
    app: portal-noticias
